name: Meraki MX65W Toolchain Builder

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: openwrt-23.05
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: 1. Đọc mã nguồn Repo
      uses: actions/checkout@v4

    - name: 2. Cài đặt các thư viện Linux biên dịch
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo timedatectl set-timezone "$TZ"

    - name: 3. Tải mã nguồn gốc OpenWrt Core
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt

    - name: 4. Cập nhật gói phần mềm Feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 5. Khởi tạo cấu hình mặc định phần cứng
      run: |
        cd openwrt
        echo "CONFIG_TARGET_ipq806x=y" > .config
        echo "CONFIG_TARGET_ipq806x_generic=y" >> .config
        echo "CONFIG_TARGET_ipq806x_generic_DEVICE_meraki_mx65w=y" >> .config
        make defconfig

    - name: 🚀 BƯỚC TẠM DỪNG: SSH kết nối máy ảo để kiểm tra
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 60
